users+(1, 'Jane');
users+(2, 'John');
users+(3, 'Dave');
users+(4, 'Emma');
users+(5, 'Robert');
todo+(1, 'Setup pgAdmin', 2, false);
todo+(2, 'Download Git', 2, false);
todo+(3, 'Setup VS Code', 1, true);
todo+(4, 'Download PostgreSQL', 2, false);
todo+(5, 'Install server', 2, false);
todo+(6, 'Create superuser', 2, false);
todo+(7, 'Create database', 2, false);
todo+(8, 'Create tables', 2, false);
todo+(9, 'Wash the dishes', 3, false);
todo+(10, 'Read the PostgreSQL manual', 4, false);
todo+(11, 'Exercise', 3, false);
todo+(12, 'Wake up in time!', 5, true);
todo+(13, 'Go to the gym', 3, false);
todo+(14, 'Wash the dishes', 5, true);
