INSERT INTO users  VALUES (1, 'Jane');
INSERT INTO users  VALUES (2, 'John');
INSERT INTO users  VALUES (3, 'Dave');
INSERT INTO users  VALUES (4, 'Emma');
INSERT INTO users  VALUES (5, 'Robert');
INSERT INTO todo   VALUES (1, 'Setup pgAdmin', 2, false);
INSERT INTO todo   VALUES (2, 'Download Git', 2, false);
INSERT INTO todo   VALUES (3, 'Setup VS Code', 1, true);
INSERT INTO todo   VALUES (4, 'Download PostgreSQL', 2, false);
INSERT INTO todo   VALUES (5, 'Install server', 2, false);
INSERT INTO todo   VALUES (6, 'Create superuser', 2, false);
INSERT INTO todo   VALUES (7, 'Create database', 2, false);
INSERT INTO todo   VALUES (8, 'Create tables', 2, false);
INSERT INTO todo   VALUES (9, 'Wash the dishes', 3, false);
INSERT INTO todo   VALUES (10, 'Read the PostgreSQL manual', 4, false);
INSERT INTO todo   VALUES (11, 'Exercise', 3, false);
INSERT INTO todo   VALUES (12, 'Wake up in time!', 5, true);
INSERT INTO todo   VALUES (13, 'Go to the gym', 3, false);
INSERT INTO todo   VALUES (14, 'Wash the dishes', 5, true);
